# Generated by Django 5.2.1 on 2025-05-19 07:05

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0014_remove_groupmessage_read_groupmessage_read_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='read_by',
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
